#!/usr/bin/env bash
# Detects system and library versions relevant to the BillardBall project
# and writes a report to plan/system.txt next to this script.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$SCRIPT_DIR/system.txt"

detect() {
    local label="$1"
    local cmd="$2"
    local value
    value=$(eval "$cmd" 2>/dev/null) || value="not found"
    printf "%-12s: %s\n" "$label" "$value"
}

{
echo "System Information"
echo "=================="
echo "Recorded: $(date +%Y-%m-%d)"
echo ""

echo "OS"
echo "--"
detect "Platform"  'uname -s'
detect "Kernel"    'uname -r'
detect "Distro"    'lsb_release -d 2>/dev/null | cut -f2-'
detect "Arch"      'uname -m'
echo ""

echo "Compiler"
echo "--------"
detect "g++"       'g++ --version | head -1'
detect "clang++"   'clang++ --version | head -1'
echo ""

echo "Build"
echo "-----"
detect "CMake"     'cmake --version | head -1 | sed "s/cmake version //"'
detect "make"      'make --version | head -1'
detect "ninja"     'ninja --version'
echo ""

echo "Libraries"
echo "---------"
detect "GLFW"      'pkg-config --modversion glfw3'
detect "OpenGL"    'pkg-config --modversion gl'
detect "GLM"       'pkg-config --modversion glm'
detect "GLAD"      'grep "OpenGL loader generated by glad" '"$SCRIPT_DIR"'/../glad/include/glad/glad.h | grep -oP "glad \K[0-9.]+"'

GLAD_API=$(grep -- '--api=' "$SCRIPT_DIR/../glad/include/glad/glad.h" 2>/dev/null \
    | grep -oP '"gl=[^"]*"' | head -1 || echo "not found")
GLAD_PROFILE=$(grep -- '--profile=' "$SCRIPT_DIR/../glad/include/glad/glad.h" 2>/dev/null \
    | grep -oP '"[a-z]+"' | head -1 || echo "not found")
printf "%-12s: api=%s profile=%s\n" "GLAD target" "$GLAD_API" "$GLAD_PROFILE"

detect "glxinfo GL" 'glxinfo | grep "OpenGL version string" | sed "s/.*: //"'
echo ""

echo "Runtime"
echo "-------"
if grep -qi microsoft /proc/version 2>/dev/null; then
    echo "WSL2        : yes"
else
    echo "WSL2        : no"
fi
detect "Display"   'echo "${DISPLAY:-not set}"'
detect "WAYLAND"   'echo "${WAYLAND_DISPLAY:-not set}"'

} > "$OUT"

echo "Written to $OUT"
